/** Registers every phase and mini game with the engine. Import once from the server adapter (and tests). */
import '../lobby.ts';
import '../toys/calibrate.ts';
import '../toys/reaction.ts';
import './minigame.ts';
import './flow.ts';
import './games/lun.ts';
import './games/stopwatch.ts';
import './games/count.ts';
import './games/tug.ts';
import './games/hunter.ts';
import '../board/board.ts';
import './games/quickdraw.ts';
import './games/trample.ts';
import './games/doors.ts';
import './games/sonar.ts';
import './games/raft.ts';
import './games/tower.ts';
import './games/herd.ts';
import './games/oddone.ts';
import './games/whowrote.ts';
import './games/predict.ts';
// After the board: the endgame wraps the board's flow steps, and duels wrap the endgame's.
import './endgame.ts';
import './duels.ts';

export * from './state.ts';
export * from './minigame.ts';
export * from './payout.ts';
export * from './flow.ts';
export { lunPlaces } from './games/lun.ts';
export { stopwatchScore } from './games/stopwatch.ts';
export { countGrade } from './games/count.ts';
export * from '../board/generate.ts';
export * from '../board/state.ts';
export { formatFromColours, initBoard } from '../board/board.ts';
export * from './endgame.ts';
export { hunterZones, caught } from './games/hunter.ts';
export * from '../simulate.ts';
export * from './items.ts';
export * from './duels.ts';
export { quickDrawScore } from './games/quickdraw.ts';
export { scoreTrampleRound, trampleZones } from './games/trample.ts';
export { chooseTraps, doorCount } from './games/doors.ts';
export { blurred, scoreNets } from './games/sonar.ts';
export { islandReward, hazardChance } from './games/raft.ts';
export { resolveTower, rowStable, towerRows } from './games/tower.ts';
export { applyMerges, scoreHerd, mergeQuorum } from './games/herd.ts';
export { accusedFrom, scoreOdd } from './games/oddone.ts';
export { scoreWho } from './games/whowrote.ts';
export { actualRanks, scorePrediction } from './games/predict.ts';
export * from './packs.ts';
