/**
 * Prompt packs for the word games. All original. Hosts can add their own packs later; these are
 * the defaults, kept family-friendly enough for most friend groups.
 */

/** Herd Mentality: answer what you think most people will say. */
export const HERD_PROMPTS = [
  'A pizza topping',
  'A colour for a car',
  'Something you find at the beach',
  'A breakfast food',
  'An animal on a farm',
  'Something in a school bag',
  'A board game',
  'A fruit that is yellow',
  'A superhero',
  'Something you do on a rainy day',
  'A sport played with a ball',
  'A famous wizard',
  'Something you plug in',
  'A type of dog',
  'Something at a birthday party',
  'A vegetable kids hate',
  'A reason to be late',
  'Something in a fridge',
  'A musical instrument',
  'A planet',
  'Something that buzzes',
  'A holiday destination',
  'Something you lose all the time',
  'A snack at the cinema',
  'A job in a hospital',
  'Something with wheels',
  'A thing in a toolbox',
  'A kitchen appliance',
  'A cartoon character',
  'Something you find in space',
  'A way to get to work',
  'A drink at a party',
  'A season',
  'Something that is cold',
  'A shape',
  'A room in a house',
  'Something people collect',
  'A fairy tale character',
  'A reason to call in sick',
  'An ice cream flavour',
  'Something in a garden',
  'A word that means happy',
  'A famous tower',
  'A type of shoe',
  'Something at a wedding',
  'An insect',
  'A dessert',
  'Something that smells good',
  'A bird',
  'A thing you do before bed',
  'A job that wears a uniform',
  'A sandwich filling',
  'Something in a pencil case',
  'A thing that is loud',
  'A pet name for a goldfish',
  'A smartphone app',
  'Something sticky',
  'A thing at a zoo',
  'A reason to celebrate',
  'A popular baby name',
  'Something you wear on your head',
  'A crisp flavour',
  'A card game',
  'Something with stripes',
  'A place to hide',
  'A thing pirates have',
  'A body of water',
  'Something green',
  'A soup',
  'A thing in a hospital',
  'Something you say to a baby',
  'A famous painting',
  'A type of weather',
  'A thing you pack for camping',
  'Something magicians use',
  'A cheese',
  'A thing that bounces',
  'A cake flavour',
  'A spooky creature',
  'A thing on a keyboard',
];

/** Unique mode (the reverse of Herd): score only for answers nobody else gave. */
export const UNIQUE_CATEGORIES = [
  'Name an animal',
  'Name a country',
  'Name a fruit',
  'Name a colour',
  'Name a job',
  'Name a food you eat with a spoon',
  'Name something in a kitchen',
  'Name a sport',
  'Name a famous city',
  'Name something round',
  'Name a musical instrument',
  'Name a piece of clothing',
  'Name something that flies',
  'Name a vegetable',
  'Name a thing in a bathroom',
  'Name a board or video game',
  'Name a word that rhymes with cat',
  'Name a chocolate bar',
  'Name something you can drink',
  'Name a body part',
  'Name something made of wood',
  'Name a hobby',
  'Name a mythical creature',
  'Name a tool',
  'Name something in the sky',
  'Name a flower',
  'Name a type of transport',
  'Name something that is red',
  'Name a dance',
  'Name a sea creature',
  'Name a word that starts with Z',
  'Name a thing you find in an office',
  'Name a breakfast cereal',
  'Name a type of bread',
  'Name a famous scientist',
  'Name something that can be broken',
  'Name a nut',
  'Name a herb or spice',
  'Name a card game',
  'Name something you take on holiday',
];

/** Odd One Out: most players get the first word; the imposter(s) get the second. */
export const ODD_PAIRS: [string, string][] = [
  ['Beach', 'Desert'],
  ['Coffee', 'Tea'],
  ['Cat', 'Fox'],
  ['Guitar', 'Violin'],
  ['Pizza', 'Pie'],
  ['Moon', 'Sun'],
  ['Train', 'Tram'],
  ['Castle', 'Palace'],
  ['Snow', 'Rain'],
  ['Doctor', 'Nurse'],
  ['Football', 'Rugby'],
  ['Pencil', 'Crayon'],
  ['Shark', 'Dolphin'],
  ['Wedding', 'Birthday'],
  ['Library', 'Bookshop'],
  ['Pirate', 'Viking'],
  ['Apple', 'Pear'],
  ['Ghost', 'Zombie'],
  ['Bicycle', 'Scooter'],
  ['Cinema', 'Theatre'],
  ['Mountain', 'Volcano'],
  ['Spoon', 'Ladle'],
  ['Lion', 'Tiger'],
  ['Pyjamas', 'Dressing gown'],
  ['Candle', 'Torch'],
  ['Bank', 'Casino'],
  ['Forest', 'Jungle'],
  ['Robot', 'Alien'],
  ['Honey', 'Syrup'],
  ['Airport', 'Train station'],
  ['Dentist', 'Barber'],
  ['Circus', 'Zoo'],
  ['Umbrella', 'Raincoat'],
  ['Chess', 'Draughts'],
  ['Submarine', 'Ship'],
  ['Ninja', 'Samurai'],
  ['Cupcake', 'Muffin'],
  ['Lighthouse', 'Windmill'],
  ['Wizard', 'Witch'],
  ['Keyboard', 'Piano'],
  ['Igloo', 'Tent'],
  ['Carrot', 'Parsnip'],
  ['Hospital', 'Pharmacy'],
  ['Balloon', 'Bubble'],
  ['River', 'Canal'],
  ['Crown', 'Tiara'],
  ['Owl', 'Bat'],
  ['Postcard', 'Letter'],
  ['Skateboard', 'Surfboard'],
  ['Museum', 'Gallery'],
  ['Farmer', 'Gardener'],
  ['Magnet', 'Glue'],
  ['Popcorn', 'Crisps'],
  ['Trumpet', 'Saxophone'],
  ['Mermaid', 'Fairy'],
  ['Helicopter', 'Aeroplane'],
  ['Map', 'Compass'],
  ['Spider', 'Ant'],
  ['Jeans', 'Leggings'],
  ['Ketchup', 'Mustard'],
  ['Snowman', 'Sandcastle'],
  ['Detective', 'Spy'],
  ['Fireworks', 'Bonfire'],
  ['Teacher', 'Coach'],
  ['Swimming pool', 'Bath'],
  ['Clock', 'Calendar'],
  ['Dragon', 'Dinosaur'],
  ['Picnic', 'Barbecue'],
  ['Sofa', 'Bed'],
  ['Penguin', 'Puffin'],
  ['Marathon', 'Sprint'],
  ['Hammer', 'Axe'],
  ['Mirror', 'Window'],
  ['Pancake', 'Waffle'],
  ['Tornado', 'Earthquake'],
  ['King', 'President'],
  ['Hotel', 'Hostel'],
  ['Violin', 'Cello'],
  ['Motorbike', 'Car'],
  ['Parrot', 'Peacock'],
];

/** Who Wrote That?: open prompts whose answers say something about the writer. */
export const WHO_WROTE_PROMPTS = [
  'The worst possible name for a pet',
  'A terrible slogan for a dentist',
  'What your fridge would say if it could talk',
  'A bad superpower to have',
  'The title of your autobiography',
  'Something you should never say at a wedding',
  'A new flavour of crisps',
  'The worst thing to hear from a pilot',
  'A rejected name for a theme park ride',
  'Your secret talent (real or not)',
  'The best excuse for missing a party',
  'What aliens think humans do all day',
  'A strange thing to collect',
  'The name of your future band',
  'A terrible idea for a restaurant',
  'The worst thing to find in your sandwich',
  'A motto for a lazy superhero',
  'What the cat is really thinking',
  'The last thing you would want to hear from a barber',
  'A new holiday everyone should celebrate',
  'A useless invention',
  'Your go-to karaoke song',
  'What you would do with a free afternoon',
  'The most overrated food',
  'A bad name for a boat',
  'Something you would put in a time capsule',
  'The worst present to give a grandparent',
  'A job you would be terrible at',
  'What a ghost does on its day off',
  'The first rule of your secret club',
  'A rejected Olympic sport',
  'Your dream holiday in three words',
  'A suspicious thing to say at airport security',
  'What your houseplants gossip about',
  'A terrible name for a perfume',
  'The worst advice to give a new driver',
  'A new word for being tired',
  'What you would name a pet dragon',
  'Something you are secretly proud of',
  'A terrible first line of a novel',
  'The most useless school subject',
  'What a dog would tweet',
  'Your ideal pizza topping combination',
  'A bad name for a sports team',
  'What you would say to a talking squirrel',
  'The strangest food combination you enjoy',
  'A warning label for yourself',
  'The worst place to hold a birthday party',
  'Something you would ban if you ruled the world',
  'A fortune cookie message nobody wants',
  'The name of a very boring film',
  'A skill you would like to learn overnight',
  'What robots dream about',
  'A terrible thing to shout in a library',
  'Your perfect lazy Sunday',
  'A new rule for board games',
  'What your phone would complain about',
  'The worst thing to forget on holiday',
  'A villain name for your neighbour',
  'An unusual pizza delivery',
];

/** Predict the Crowd: pick your answer, then rank the four options by how the room voted. */
export const PREDICT_QUESTIONS: { q: string; options: [string, string, string, string] }[] = [
  { q: 'Best time of day?', options: ['Morning', 'Afternoon', 'Evening', 'Late night'] },
  { q: 'Best pet?', options: ['Dog', 'Cat', 'Fish', 'Rabbit'] },
  { q: 'Pick a superpower', options: ['Flying', 'Invisibility', 'Teleporting', 'Mind reading'] },
  { q: 'Best pizza topping?', options: ['Pepperoni', 'Mushroom', 'Pineapple', 'Just cheese'] },
  { q: 'Dream holiday?', options: ['Beach', 'City break', 'Mountains', 'Staying home'] },
  { q: 'Best season?', options: ['Spring', 'Summer', 'Autumn', 'Winter'] },
  { q: 'Tea or coffee?', options: ['Tea', 'Coffee', 'Both', 'Neither'] },
  { q: 'How do you eat an ice cream?', options: ['Lick', 'Bite', 'Spoon', 'Let it melt'] },
  { q: 'Best way to travel?', options: ['Train', 'Car', 'Plane', 'Bike'] },
  { q: 'Pick a board game', options: ['Chess', 'Monopoly', 'Scrabble', 'Cluedo'] },
  { q: 'Morning routine first step?', options: ['Phone', 'Shower', 'Coffee', 'Snooze'] },
  { q: 'Best biscuit?', options: ['Chocolate chip', 'Digestive', 'Custard cream', 'Shortbread'] },
  { q: 'Would you rather live...', options: ['In a castle', 'On a boat', 'In a treehouse', 'In space'] },
  { q: 'Best film genre?', options: ['Comedy', 'Horror', 'Action', 'Romance'] },
  { q: 'Favourite meal of the day?', options: ['Breakfast', 'Lunch', 'Dinner', 'Midnight snack'] },
  { q: 'Best dinosaur?', options: ['T-Rex', 'Triceratops', 'Velociraptor', 'Diplodocus'] },
  { q: 'Pick a potato', options: ['Chips', 'Mashed', 'Roast', 'Jacket'] },
  { q: 'Best weather?', options: ['Sunny', 'Snowy', 'Rainy', 'Stormy'] },
  { q: 'Most useful invention?', options: ['Internet', 'Wheel', 'Fridge', 'Toilet'] },
  { q: 'Best party food?', options: ['Pizza', 'Crisps', 'Sausage rolls', 'Cake'] },
  { q: 'Which would you save in a fire?', options: ['Phone', 'Photos', 'Wallet', 'Pet'] },
  { q: 'Best sandwich?', options: ['Cheese', 'Ham', 'BLT', 'Peanut butter'] },
  { q: 'Pick a fantasy job', options: ['Dragon tamer', 'Wizard', 'Knight', 'Pirate'] },
  { q: 'Best cereal milk?', options: ['Cow', 'Oat', 'Almond', 'No milk'] },
  { q: 'Most scary?', options: ['Spiders', 'Heights', 'Clowns', 'The dark'] },
  { q: 'Best sport to watch?', options: ['Football', 'Tennis', 'F1', 'None'] },
  { q: 'Ideal Friday night?', options: ['Going out', 'Takeaway', 'Games night', 'Early bed'] },
  { q: 'Best chocolate?', options: ['Milk', 'Dark', 'White', 'None'] },
  { q: 'Which animal would win a race?', options: ['Cheetah', 'Horse', 'Ostrich', 'Greyhound'] },
  { q: 'How do you pay?', options: ['Card', 'Phone', 'Cash', 'Someone else pays'] },
  { q: 'Best way to spend a snow day?', options: ['Snowball fight', 'Sledging', 'Under a blanket', 'Snowman'] },
  { q: 'Pick a room', options: ['Kitchen', 'Bedroom', 'Living room', 'Garden'] },
  { q: 'Best sweet?', options: ['Gummy bears', 'Chocolate', 'Lollipop', 'Mints'] },
  { q: 'Which would you give up?', options: ['Music', 'Films', 'Social media', 'Takeaways'] },
  { q: 'Best bread?', options: ['White', 'Brown', 'Sourdough', 'Bagel'] },
  { q: 'What wakes you up?', options: ['Alarm', 'Sunlight', 'Pet', 'Hunger'] },
  { q: 'Most fun theme park ride?', options: ['Rollercoaster', 'Log flume', 'Ghost train', 'Teacups'] },
  { q: 'Best way to eat eggs?', options: ['Scrambled', 'Fried', 'Boiled', 'Poached'] },
  { q: 'Pick a musical instrument to master', options: ['Piano', 'Guitar', 'Drums', 'Violin'] },
  { q: 'Best topping for chips?', options: ['Salt & vinegar', 'Ketchup', 'Cheese', 'Gravy'] },
  { q: 'Where would you hide treasure?', options: ['Under the bed', 'In the garden', 'In a book', 'Freezer'] },
  { q: 'Pick a colour', options: ['Blue', 'Red', 'Green', 'Purple'] },
  { q: 'Best time to exercise?', options: ['Morning', 'Lunch', 'Evening', 'Never'] },
  { q: 'Which pet name?', options: ['Biscuit', 'Max', 'Luna', 'Sir Fluffington'] },
  { q: 'Best holiday?', options: ['Christmas', 'Halloween', 'Birthdays', 'New Year'] },
  { q: 'Best cartoon cat?', options: ['Garfield', 'Tom', 'Sylvester', 'Hello Kitty'] },
  { q: 'Which would you rather be?', options: ['Rich', 'Famous', 'Clever', 'Lucky'] },
  { q: 'Best smell?', options: ['Fresh bread', 'Rain', 'Coffee', 'Cut grass'] },
  { q: 'Best way to relax?', options: ['Bath', 'Nap', 'Walk', 'Video games'] },
  { q: 'Best dessert?', options: ['Ice cream', 'Cheesecake', 'Brownie', 'Fruit salad'] },
  { q: 'What do you do first at a party?', options: ['Find food', 'Find friends', 'Find the host', 'Find the exit'] },
  { q: 'Best way to learn?', options: ['Reading', 'Watching', 'Doing', 'Asking'] },
  { q: 'Pick a planet to visit', options: ['Mars', 'Saturn', 'Jupiter', 'Venus'] },
  { q: 'Best side of the bed?', options: ['Left', 'Right', 'Middle', 'Diagonal'] },
  { q: 'Best pasta shape?', options: ['Spaghetti', 'Penne', 'Fusilli', 'Lasagne'] },
  { q: 'Most annoying sound?', options: ['Alarm clock', 'Chewing', 'Nails on a board', 'Snoring'] },
  { q: 'Which would you learn?', options: ['A language', 'Cooking', 'Magic tricks', 'Juggling'] },
  { q: 'Best way to say goodbye?', options: ['Hug', 'Wave', 'High five', 'Just leave'] },
  { q: 'Best game night snack?', options: ['Popcorn', 'Nachos', 'Chocolate', 'Fruit'] },
  { q: 'Which is the best number?', options: ['3', '7', '8', '42'] },
];
