import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1920, height: 1080 } });
await p.goto('http://localhost:5173/dev/board?n=' + (process.argv[2] ?? '6'));
const host = p.frameLocator('iframe[title="Host screen"]');
await host.locator('.board-svg').waitFor({ timeout: 60000 });
await p.waitForTimeout(1500);
await host.locator('.board-svg').screenshot({ path: 'C:/Users/Harry/AppData/Local/Temp/claude/C--Dev-PartyGame/5c965114-637a-4cb6-ab5c-5cb0ec95979a/scratchpad/' + (process.argv[3] ?? 'board.png') });
const player = p.frameLocator('iframe[title="Player screen"]');
await player.locator('.bp-map').screenshot({ path: 'C:/Users/Harry/AppData/Local/Temp/claude/C--Dev-PartyGame/5c965114-637a-4cb6-ab5c-5cb0ec95979a/scratchpad/' + (process.argv[3] ?? 'board.png').replace('.png', '-phone.png') }).catch(() => {});
await b.close();
