import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1920, height: 1080 }, deviceScaleFactor: 2 });
await p.goto('http://localhost:5173/dev/board?n=' + (process.argv[2] ?? '4'));
const host = p.frameLocator('iframe[title="Host screen"]');
await host.locator('.board-svg').waitFor({ timeout: 60000 });
await p.waitForTimeout(1500);
const box = await host.locator('.board-svg').boundingBox();
await p.screenshot({ path: 'C:/Users/Harry/AppData/Local/Temp/claude/C--Dev-PartyGame/5c965114-637a-4cb6-ab5c-5cb0ec95979a/scratchpad/zoom-start.png', clip: { x: box.x, y: box.y, width: box.width * 0.42, height: box.height * 0.42 } });
await b.close();
